apiVersion: v1
kind: ConfigMap
metadata:
  name: verdure-config
  namespace: verdure
data:
  DB_HOST: "db-service"
  DB_USER: "root"
  PREDICTOR_URL: "http://ai-chatbot-service:5000/chat"
  PREDICTOR_PORT: "5000"
  OMP_NUM_THREADS: "1"
  TOKENIZERS_PARALLELISM: "false"