apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  namespace: verdure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 
  resources:
    requests:
      storage: 2Gi