apiVersion: v1
kind: Service
metadata:
  name: verdure-ai-chatbot
  namespace: verdure
spec:
  selector:
    app: verdure-ai-chatbot
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
