apiVersion: v1
kind: Service
metadata:
  name: verdure-backend
  namespace: verdure
spec:
  selector:
    app: verdure-backend
  ports:
    - name: http
      port: 3030
      targetPort: 3030
      nodePort: 30303
  type: NodePort
