resources:
  - namespace.yaml
  - configmap.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ai-chatbot-deployment.yaml
  - ai-chatbot-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - hpa-ai-chatbot.yaml
